[package]
name = "chainjump"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.4.0", features = ["full"] }
axum = "0.7.7"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
